[prod]
10.0.5.5 ansible_user=student ansible_connection=ssh ansible_become_password="{{ ansible_password }}"
[local]
localhost ansible_user=student ansible_connection=local ansible_become_password="{{ ansible_password }}"
